# Generated by Django 6.0.8 on 2026-10-07 07:16

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    # Everyone who signed up before email codes existed can still log in.
    User = apps.get_model('accounts', 'User')
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('wrong_attempts', models.PositiveSmallIntegerField(default=0)),
                ('hour_started_at', models.DateTimeField(blank=True, null=True)),
                ('sends_this_hour', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
