# Generated by Django 6.0.8 on 2026-10-06 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_removed_statuses(apps, schema_editor):
    """"processing" and "completed" no longer exist: move them to their new equivalents."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='processing').update(status='confirmed')
    Order.objects.filter(status='completed').update(status='delivered')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('ready_for_pickup', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('ready_for_pickup', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('ready_for_pickup', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        # Going back can't tell the mapped rows apart, so the reverse does nothing.
        migrations.RunPython(map_removed_statuses, migrations.RunPython.noop),
    ]
