# Generated by Django 6.0.8 on 2026-09-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_copy_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
